Market.WebSite/Market.WebSite/Models/Order/CreateOrderModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.WebSite.Models.Order
{
    public class CreateOrderModel
    {
        [Required(ErrorMessage = "*")]
        [Display(Name = "Имя")]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Display(Name = "Фамилия")]
        [StringLength(50)]
        public string LastName { get; set; }

        [Display(Name = "Отчество")]
        [StringLength(50)]
        public string Patronymic { get; set; }

        [Display(Name = "Номер телефона")]
        [Required(ErrorMessage = "*")]
        [StringLength(20)]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

		[Display(Name = "Email")]
		[StringLength(255)]
		public string Email { get; set; }

		[Display(Name = "Город")]
		[StringLength(255)]
		public string Address { get; set; }

        [Required]
        [HiddenInput(DisplayValue = false)]
        [Range(1, 100)]
        public int Count { get; set; }

        [Display(Name = "Комментарий к заказу")]
        [StringLength(2500)]
        public string Comment { get; set; }
    }
}

Market.WebSite/Market.WebSite/Models/Order/OrderDetailModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Market.WebSite.Models.Order
{
    public class OrderDetailModel
    {
	    public int OrderId { get; set; }

        [Display(Name = "Номер заказа")]
        public int OrderNumber { get { return OrderId + 1015; } }

	    [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Display(Name = "Отчество")]
        public string Patronymic { get; set; }

        [Display(Name = "Номер телефона")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        [Display(Name = "Адрес")]
        public string Address { get; set; }

        [Display(Name = "Количество рыб")]
        public int Count { get; set; }

        [Display(Name = "Комментарий к заказу")]
        public string Comment { get; set; }

        public Guid AlternativeId { get; set; }
    }
}

Market.WebSite/Market.WebSite/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;

namespace Market.WebSite.Controllers
{
    //[Context]
    //[Logging]
    public class BaseController : Controller
    {
        public void SetError<T>(Expression<Func<T>> memberExpression, string message)
        {
            var expressionBody = (MemberExpression)memberExpression.Body;
            ModelState.AddModelError(expressionBody.Member.Name, message);
        }

        public void SetError(string message)
        {
            ModelState.AddModelError("", message);
        }
    }

}

Market.WebSite/Market.WebSite/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.WebSite.Controllers
{
    public class BlogController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }


    }
}

Market.WebSite/Market.WebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Market.Data.Context;

namespace Market.WebSite.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }


        public ActionResult Info()
        {
            return View();
        }

        public ActionResult Delivery()
        {
            return View();
        }

        public ActionResult Payment()
        {
            return View();
        }

		public ActionResult PageNotFound()
		{
			return View();
		}

		public ActionResult ServerError()
		{
			return View();
		}
    }
}

Market.WebSite/Market.WebSite/Controllers/OrderController.cs
using System;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Market.Data.Context;
using Market.WebSite.Models.Order;

namespace Market.WebSite.Controllers
{
    public class OrderController : BaseController
    {

        [HttpGet]
        public async Task<ActionResult> Index(Guid id)
        {
            Order order;
            using (var context = new MarketContext())
                order = await context.Orders.Where(o => o.AlternativeId == id).SingleOrDefaultAsync();

            if (order == null) throw new ArgumentException("Ошибка");

            var model = new OrderDetailModel
            {
                OrderId = order.Id,
                Count = order.Count,
                Address = order.Address,
                FirstName = order.FirstName,
                LastName = order.LastName,
                Patronymic = order.Patronymic,
                PhoneNumber = order.PhoneNumber,
                Comment = order.Comment,
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateOrderModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Заполните все поля";
                return View();
            }

            var now = DateTime.UtcNow;
            var order = new Order
                {
                    Address = model.Address,
                    CreationDate = now,
                    ModificationDate = now,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PhoneNumber = model.PhoneNumber,
                    Patronymic = model.Patronymic,
                    Count = model.Count,
                    Comment = model.Comment
                };

            using (var context = new MarketContext())
            {
                context.Orders.Add(order);
                await context.SaveChangesAsync();
            }

            var createdOrderModel = new OrderDetailModel
            {
                OrderId = order.Id,
                Count = order.Count,
                Address = order.Address,
                FirstName = order.FirstName,
                LastName = order.LastName,
                Patronymic = order.Patronymic,
                PhoneNumber = order.PhoneNumber,
                Comment = order.Comment,
                AlternativeId = order.AlternativeId
            };

            Market.Mailer.Mail.SendEmail("Заказ" + createdOrderModel.OrderNumber,
                Market.Common.MailRenderer.RenderPartialViewToString(this, "MailBody", createdOrderModel),
                new[] { ConfigurationManager.AppSettings["EmailLogin"], "Pahkin@bk.ru" });

            return RedirectToAction("Index", "Order", new { id = order.AlternativeId });
        }


        public ActionResult MailBody(OrderDetailModel model)
        {
            return View(model);
        }

    }
}

Market.WebSite/Market.WebSite/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.WebSite.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
    }
}

Market.WebSite/Market.WebSite/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Блог";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<input type="hidden" id="activetab" value="blogtab">
<div class="container">
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-9">
            <div class="blog-post-area">
                <h2 class="title text-center">Последнее в нашем блоге</h2>


                <div class="single-blog-post">
                    <h3>Польза форели</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-calendar"></i>12 февраля, 2016</li>
                        </ul>
                    </div>
                    <a>
                        <img src="~/Content/images/blog/blog-photo2.png" alt="">
                    </a>
                    <div class="blog-post">
                        <div class="blog-post-title">
                            <p>
                                Форель является источником многих питательных веществ, полезных для организма человека. Прежде всего, это полиненасыщенные Омега-3 жиры. Эти жиры являются жизненно важными для нормального функционирования головного мозга, состояния кожи, волос, уменьшают накопление вредных веществ в организме. Омега-3 ненасыщенные жиры снижают уровень плохого холестерина, что предотвращает многие сердечно-сосудистые заболевания, в том числе и атеросклероз, инсульт и инфаркт.Кроме того омега-3 жиры обладают противовоспалительными свойствами и будут полезны при воспалительных заболеваниях костей, в частности артрита.
                            </p>
                        </div>
                        <div class="blog-post-inner">
                            <p>
                                <br/>Форель является хорошим источником минералов, включая селен и железо. Селен необходим для нормальной функции щитовидной железы, для иммунной системы. Селен также один из мощных антиоксидантов, который помогает бороться с вредными радикалами, в частности, тяжелыми металлами.<br/> Железо необходимо для нормального состава крови, предупреждения анемии. Влияет этот элемент и на внешний вид: волосы и ногти также нуждаются в железе.
                                <br/>Присутствуют в форели также такие важные элементы, как йод, магний, кальций, калий и, конечно, фосфор. Форель источник таких витаминов, как витамин А. D, ряда витаминов группы В. Витамин В12, это витамин, который плохо усваивается из биодобавок. Он необходим для нормальной функции головного мозга, развития костей и мышц, нормальной работы пищеварительного тракта, профилактики сердечно-сосудистых заболеваний, для поддержания организма в тонусе.
                                <br/>Форель очень важна детскому организму. Полезна эта рыба и беременным женщинам. Форель относится к низкокалорийным продуктам, поэтому может не обеспечить полного насыщения, как например, мясо. Однако это является недостатком только для любителей плотного обеда. Те же, кто следит за фигурой, останутся непременно довольны – диетологи рекомендуют употреблять форель в целях похудения.
                                Витамин В3 – ниацин, важен для нервной системы и мозга.
                                Витамин В6 нужен женщинам, может улучшить состояние во время ПМС и менопаузы.
                                Форель очень полезно включить в свое меню людям:
                                С риском сердечно-сосудистых заболеваний;
                                С высоким уровнем гомоцистеина;
                                У кого сухая кожа, волосы, слоятся ногти;
                                С заболеваниями костей, в частности артритом;
                                Женщинам, желающим забеременеть;
                                Мужчинам для увеличения подвижности сперматозоидов;
                                У кого слабая иммунная система;
                                Страдающим сахарным диабетом или гипогликемией;
                            </p>
                        </div>
                    </div>
                    <a class="btn btn-primary blog-post-button">Читать дальше</a>
                </div>
                <div class="single-blog-post">
                    <h3>Форель в кулинарии</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-calendar"></i>5 февраля, 2016</li>
                        </ul>
                    </div>
                    <a>
                        <img src="~/Content/images/blog/blog-photo3.png" alt="">
                    </a>
                    <div class="blog-post">
                        <div class="blog-post-title">
                            <p>
                                В кулинарии используются все виды форели. К этой рыбе можно применять любой вид кулинарной обработки: варить, жарить, тушить, запекать, солить.
                            </p>
                        </div>
                        <div class="blog-post-inner">
                            <p>
                                Форель – это любимая рыба всех диетологов мира. Несмотря на то, что форель относится к жирным рыбам, в 100 граммах этого продукта содержится всего : 88.0 ккал. И в то же время 20 грамм белка.Диетологи рекомендуют включать форель в свое меню два, три раза в неделю.<br/>
                                Форель лидирует среди диетических продуктов, обладает всеми свойствами необходимыми для полноценного функционирования организма. Белок легко усваивается, а жир не откладывается, а наоборот, выполняет роль катализатора в расщеплении жиров. Форель способствует похудению. Правильное применение для снижения веса – это сочетание с зеленью, овощами, специями, лимонным соком.<br/>
                                • Калорийность: 88.0 ккал<br />
                                • Белки: 20 г<br />
                                • Жиры: 2.0 г<br />
                            </p>
                        </div>
                    </div>
                    <a class="btn btn-primary blog-post-button">Читать дальше</a>
                </div>

                <div class="single-blog-post">
                    <h3>Форель в кулинарии</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-calendar"></i>28 января, 2016</li>
                        </ul>
                    </div>
                    <a>
                        <img src="~/Content/images/blog/blog-photo1.png" alt="">
                    </a>
                    <div class="blog-post">
                        <div class="blog-post-title">
                            <p>
                                Форель на Руси была пищей аристократов и знати. Она вкусна, нежна и полезна. В народе называется «красная рыба» и входит в группу элитных продуктов.
                            </p>
                        </div>
                        <div class="blog-post-inner">
                            <p>
                                Для жизни форели нужно несколько основных условий: это холодная чистая вода, наличие хорошей еды, место где можно спрятаться от хищников и чистый гравий, чтобы отложить икру. Отсюда можно сделать вывод, что форель один из самых экологически чистых видов рыб.<br/>
                                 Форель – уникальная рыба. При помощи этой рыбы даже осуществляют диагностику водной среды (при наличии токсических веществ форель погибает).
                            </p>
                        </div>
                    </div>
                    <a class="btn btn-primary blog-post-button">Читать дальше</a>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>

    </div>
</div>

Market.WebSite/Market.WebSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Market.WebSite/Market.WebSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Связаться с нами";
}
<input type="hidden" id="activetab" value="contactstab">
<div id="contact-page" class="container">
    <div class="row">
        <div class="col-sm-8">
            <div class="contact-form">
                <h2 class="title text-center">Связаться</h2>
                <div class="status alert alert-success" style="display: none"></div>
                <form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
                    <div class="form-group col-md-6">
                        <input type="text" name="name" class="form-control" required="required" placeholder="Ваше имя">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="email" name="email" class="form-control" required="required" placeholder="Email">
                    </div>
                    <div class="form-group col-md-12">
                        <input type="text" name="subject" class="form-control" required="required" placeholder="Тема">
                    </div>
                    <div class="form-group col-md-12">
                        <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Сообщение"></textarea>
                        <input type="submit" name="submit" class="btn btn-primary pull-right" value="Отправить">
                    </div>
                </form>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="contact-info">
                <h2 class="title text-center">Контакты</h2>
                <address>
                    <p>E-Shopper Inc.</p>
                    <p>935 W. Webster Ave New Streets Chicago, IL 60614, NY</p>
                    <p>Newyork USA</p>
                    <p>Mobile: +2346 17 38 93</p>
                    <p>Fax: 1-714-252-0026</p>
                    <p>Email: info@e-shopper.com</p>
                </address>
                <div class="social-networks">
                    <h2 class="title text-center">Социальные сети</h2>
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

Market.WebSite/Market.WebSite/Views/Home/Delivery.cshtml
@model dynamic

@{
    ViewBag.Title = "Доставка";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<input type="hidden" id="activetab" value="deliverytab">

<div id="contact-page" class="container">
    <div class="row">
        <div class="col-sm-1"></div>

        <div class="col-sm-9">
            <div class="contact-form">
                <h2 class="title text-center">Доставка</h2>
                <label style="color: #696763; font-size: 18px;"> Всегда рады доставить Вам продукт первой свежести! 
                <br/>Доставка осуществляется по вторникам.
                <br/>Доставка от 3 рыб и больше - бесплатно.<br/> Цены на доставку:<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• по городу - 100р.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• oтдаленные районы (5,6 микрорайоны, Стрижи, Академ, Бердск) - 170р.<br /><br /> Дополнительную информацию можно получить по телефону: +7(383)-381-51-49</label>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
</div>

Market.WebSite/Market.WebSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Доставка свежей рыбы";
}
<input type="hidden" id="activetab" value="maintab">
<section id="slider">
    <!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#slider-carousel" data-slide-to="0" class=""></li>
                        <li data-target="#slider-carousel" data-slide-to="1" class="active"></li>
                        <li data-target="#slider-carousel" data-slide-to="2" class=""></li>
                    </ol>

                    <div class="carousel-inner">
                        <div class="item">
                            <div class="col-sm-6">
                                <img src="~/Content/images/home/slider-fish3.jpg" class="girl img-responsive" alt="">
                            </div>
                            <div class="col-sm-6">
                                <h2>Доставка свежей рыбы</h2>
                                <p>Самая свежая форель в Новосибирске!</p>
                                <button type="button" class="btn btn-default get" onclick="window.location.href='@Url.Action("Create", "Order")';">Заказать</button>
                            </div>

                        </div>
                        <div class="item active">
                            <div class="col-sm-6">
                                <img src="~/Content/images/home/slider-fish4.jpg" class="girl img-responsive" alt="">
                            </div>
                            <div class="col-sm-6">
                                <h2>Доставка свежей рыбы</h2>
                                <p>Самая свежая форель в Новосибирске!</p>
                                <button type="button" class="btn btn-default get" onclick=" window.location.href = '@Url.Action("Create", "Order")'; ">Заказать</button>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-sm-6">
                                <img src="~/Content/images/home/slider-fish5.jpg" class="girl img-responsive" alt="">
                            </div>
                            <div class="col-sm-6">
                                <h2>Доставка свежей рыбы</h2>
                                <p>Самая свежая форель в Новосибирске!</p>
                                <button type="button" class="btn btn-default get" onclick="window.location.href='@Url.Action("Create", "Order")';">Заказать</button>
                            </div>

                        </div>
                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
</section>

Market.WebSite/Market.WebSite/Views/Home/PageNotFound.cshtml
@{
    ViewBag.Title = "Страница не найдена";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container bigError">
    <div class="row">
        <h1>404</h1>
    </div>
    <div class="row">
        <label>Страница не найдена</label>
    </div>
    <div class="row">
        <input type="button" value="Перейти на главную" class="btn btn-primary" onclick="window.location.href='@Url.Action("Index", "Home")';" />
    </div>
</div>

Market.WebSite/Market.WebSite/Views/Home/ServerError.cshtml
@{
    ViewBag.Title = "Ошибка сервера";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container bigError">
    <div class="row">
        <h1>500</h1>
    </div>
    <div class="row">
        <label>Ошибка сервера</label>
    </div>
    <div class="row">
        <input type="button" value="Перейти на главную" class="btn btn-primary" onclick="window.location.href='@Url.Action("Index", "Home")';" />
    </div>
</div>

Market.WebSite/Market.WebSite/Views/Order/Create.cshtml
@using Market.Common
@model Market.WebSite.Models.Order.CreateOrderModel

@{
    ViewBag.Title = "Оформить заказ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="cart_items">
    <div class="container">
        <h2>Оформление заказа</h2>
        <div class="review-payment">
            <h2>Заказ и Стоимость</h2>
        </div>


        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Товар</td>
                        <td class="description">Описание</td>
                        <td class="price">Цена</td>
                        <td class="quantity">Количество</td>
                        <td class="total">Сумма</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="cart_product">
                            <a href="@Url.Action("Index", "Product")"><img src="~/Content/images/home/product1.png" alt=""></a>
                        </td>
                        <td class="cart_description">
                            <h4><a href="@Url.Action("Index", "Product")">Радужная форель</a></h4>
                        </td>
                        <td class="cart_description">
                            <h4><a>850 р.</a></h4>
                        </td>
                        <td class="cart_quantity">
                            <div class="cart_quantity_button">
                                <span class="cart_quantity_up" id="addToCartButton" onclick=" addToCart() "> + </span>
                                <input class="cart_quantity_input" id="totalCount" type="text" name="quantity" value="0" autocomplete="off" size="2" readonly>
                                <span class="cart_quantity_down" id="deleteFromCartButton" onclick=" deleteFromCart() "> - </span>
                            </div>
                        </td>
                        <td class="cart_total">
                            <p class="cart_total_price" id="totalPrice"></p>
                        </td>
                    </tr>

                </tbody>
            </table>
        </div>

        <div class="shopper-informations">
            @using (Html.BeginForm("Create", "Order", FormMethod.Post,new {id = "order-form"}))
            {
                <div class="row">
                    <div class="col-sm-4">
                        <div class="shopper-info">
                            <p>Ваши данные</p>
                            <div>
                                @Html.ValidationMessageFor(model => model.FirstName)
                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @placeholder = "Имя" } })
                            </div>
                            <div>
                                @Html.ValidationMessageFor(model => model.PhoneNumber)
                                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @placeholder = "Телефон" } })
                            </div>
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @placeholder = "Фамилия" } })
                            @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @placeholder = "Отчество" } })
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @placeholder = "Email" } })

                        </div>
                    </div>
                    <div class="col-sm-4 clearfix">
                        <div class="bill-to">
                            <p>Доставка</p>
                            <div class="form-one">
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @placeholder = "Адрес" } })
                                @Html.EditorFor(model => model.Count, new { @placeholder = "Количество", type = "number" })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="order-message">
                            <p>Комментарий к заказу</p>
                            @Html.TextAreaFor(model => model.Comment, new { @placeholder = "Ваш комментарий к заказу", rows = "12", name = "message" })
                        </div>
                    </div>
                </div>
                <div>
                    <h4 style="font-size: 14px;"><span style="color: red;">Внимание!</span> Цена приблизительная, т. к. рассчитана из среднего веса 1ой рыбы. Вес рыбы колеблется от 1.2 до 2 кг</h4>
                </div>
                <div id="orderButtons" style="display: none;">
                    <button id="create-button" class="btn btn-primary">Оформить заказ</button>
                </div>
            }
        </div>
    </div>
</section>

Market.WebSite/Market.WebSite/Views/Shared/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="@Url.Action("Index","Home")"><img class="logo-picture" src="~/Content/images/home/fish.png" alt="" /></a>
                    </div>
                </div>
                <div class="col-sm-4"></div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="@Url.Action("Index","Home")" class="maintab">Главная</a></li>
                            <li><a href="@Url.Action("Index","Blog")" class="blogtab">Блог</a></li>
                            <li><a href="@Url.Action("Delivery","Home")" class="deliverytab">Доставка</a></li>
                            <li><a href="@Url.Action("Payment","Home")" class="paymenttab">Оплата</a></li>
                            <li style="display: none;"><a href="@Url.Action("Contact","Home")" class="contactstab">Контакты</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="mainmenu_cart pull-right">
                        <ul class="nav navbar-nav">
                            <li>
                                <button class="btn btn-primary" style="margin-top: -5px;" onclick="window.location.href='@Url.Action("Create", "Order")';"><i class="fa fa-shopping-cart"></i> Корзина <b id="cartElement">(0 шт.)</b></button>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->